AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish DynamoDB configuration

Parameters:
  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  EnvironmentType:
    Type: String

Conditions:
  IsProduction:
    !Equals [!Ref EnvironmentType, prod]
  IsDev:
    !Equals [!Ref EnvironmentType, dev]

Resources:

  Raw2ZarrTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub ${StackPrefix}-Raw2Zarr
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job
          AttributeType: S
      KeySchema:
        - AttributeName: job
          KeyType: HASH



Outputs:
  Raw2ZarrTableName:
    Value: !Ref Raw2ZarrTable
  Raw2ZarrTableArn:
    Value: !GetAtt Raw2ZarrTable.Arn
