AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Topics and Queues


Parameters:
  StackPrefix:
    Type: String

Resources:


  ##### Topics #####

  IndexLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-trigger-index

  IndexDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-index-dlq


  CruiseSplitterLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-cruise-splitter

  CruiseSplitterDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-cruise-splitter-dlq

  ZarrCruiseAccumulatorLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-zarr-cruise-accumulator

  ZarrCruiseAccumulatorDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-zarr-cruise-accumulator-dlq


  RawToZarrLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-raw-to-zarr

  RawToZarrDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-raw-to-zarr-dlq

  ResampleZarrStoreTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-resample-zarr

  ResampleZarrStoreDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-resample-zarr-dlq

#  ZarrInitializerLambdaTopic:
  CreateEmptyZarrStoreLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-create-empty-zarr-store


Outputs:
  IndexLambdaTopicArn:
    Value: !Ref IndexLambdaTopic
  IndexDeadLetterTopicArn:
    Value: !Ref IndexDeadLetterTopic
  CruiseSplitterLambdaTopicArn:
    Value: !Ref CruiseSplitterLambdaTopic
  CruiseSplitterDeadLetterTopicArn:
    Value: !Ref CruiseSplitterDeadLetterTopic
  ZarrCruiseAccumulatorLambdaTopicArn:
    Value: !Ref ZarrCruiseAccumulatorLambdaTopic
  ZarrCruiseAccumulatorDeadLetterTopicArn:
    Value: !Ref ZarrCruiseAccumulatorDeadLetterTopic
  RawToZarrLambdaTopicArn:
    Value: !Ref RawToZarrLambdaTopic
  RawToZarrDeadLetterTopicArn:
    Value: !Ref RawToZarrDeadLetterTopic
  ResampleZarrStoreDeadLetterTopicArn:
    Value: !Ref ResampleZarrStoreDeadLetterTopic
  ResampleZarrStoreTopicArn:
    Value: !Ref ResampleZarrStoreTopic
  CreateEmptyZarrStoreLambdaTopicArn:
    Value: !Ref CreateEmptyZarrStoreLambdaTopic




