AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Topics and Queues


Parameters:
  StackPrefix:
    Type: String

Resources:


  ##### Topics #####

  IndexLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-trigger-index

  IndexDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-index-dlq


  CruiseSplitterLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-cruise-splitter

  CruiseSplitterDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-cruise-splitter-dlq


  RawToZarrLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-raw-to-zarr

  RawToZarrDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-raw-to-zarr-dlq

#  ResampleDeadLetterTopic:
#    Type: AWS::SNS::Topic
#    Properties:
#      Tags:
#        - Key: Application
#          Value: EchoFish
#        - Key: StackPrefix
#          Value: !Ref StackPrefix
#      TopicName: !Sub ${StackPrefix}-resample-dlq

#  ZarrInitializerLambdaTopic:
  CreateEmptyZarrStoreLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-create-empty-zarr-store

  CreateEmptyZarrStoreDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-create-empty-zarr-store-dlq

Outputs:
  IndexLambdaTopicArn:
    Value: !Ref IndexLambdaTopic
  IndexDeadLetterTopicArn:
    Value: !Ref IndexDeadLetterTopic
  CruiseSplitterLambdaTopicArn:
    Value: !Ref CruiseSplitterLambdaTopic
  CruiseSplitterDeadLetterTopicArn:
    Value: !Ref CruiseSplitterDeadLetterTopic
  RawToZarrLambdaTopicArn:
    Value: !Ref RawToZarrLambdaTopic
  RawToZarrDeadLetterTopicArn:
    Value: !Ref RawToZarrDeadLetterTopic
#  ResampleDeadLetterTopicArn:
#    Value: !Ref ResampleDeadLetterTopic
  CreateEmptyZarrStoreLambdaTopicArn:
    Value: !Ref CreateEmptyZarrStoreLambdaTopic
  CreateEmptyZarrStoreDeadLetterTopicArn:
    Value: !Ref CreateEmptyZarrStoreDeadLetterTopic




