AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Topics and Queues


Parameters:
  StackPrefix:
    Type: String

Resources:


  ##### Topics #####

  IndexDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-index-dlq

  CruiseSplitterDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-cruise-splitter-dlq

  RawToZarrDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-raw-to-zarr-dlq

  ResampleDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-resample-dlq


  IndexLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-trigger-index

  CruiseSplitterLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-cruise-splitter

  RawToZarrLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-raw-to-zarr

  ZarrInitializerLambdaTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Application
          Value: EchoFish
        - Key: StackPrefix
          Value: !Ref StackPrefix
      TopicName: !Sub ${StackPrefix}-zarr-init


  ##### Topics #####


Outputs:
  IndexLambdaTopicArn:
    Value: !Ref IndexLambdaTopic
  IndexDeadLetterTopicArn:
    Value: !Ref IndexDeadLetterTopic
  CruiseSplitterDeadLetterTopicArn:
    Value: !Ref CruiseSplitterDeadLetterTopic
  RawToZarrDeadLetterTopicArn:
    Value: !Ref RawToZarrDeadLetterTopic
  ResampleDeadLetterTopicArn:
    Value: !Ref ResampleDeadLetterTopic
  CruiseSplitterLambdaTopicArn:
    Value: !Ref CruiseSplitterLambdaTopic
  RawToZarrLambdaTopicArn:
    Value: !Ref RawToZarrLambdaTopic
  ZarrInitializerLambdaTopicArn:
    Value: !Ref ZarrInitializerLambdaTopic




