AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Subscription to Topics and Queues

Parameters:
  IndexLambdaName:
    Type: String
  IndexLambdaTopicArn:
    Type: String
  IndexLambdaQueueArn:
    Type: String

Resources:

  IndexLambdaTopicToIndexLambdaQueue:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref IndexLambdaTopicArn
      Endpoint: !Ref IndexLambdaQueueArn

  IndexLambdaQueueToIndexLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IndexLambdaName
      Principal: sqs.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Ref IndexLambdaQueueArn

  IndexLambdaTopicToIndexLambdaQueuePolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref IndexLambdaTopicArn
      PolicyDocument:
        Version: 2012-10-17
        Id:
          Fn::Sub:
            - IndexLambdaTopicToIndexLambdaQueuePolicy-${StackUuid}
            - StackUuid:
                Fn::Select:
                  - "2"
                  - Fn::Split:
                      - "/"
                      - !Ref AWS::StackId
        Statement:
          - Sid: PublishToTopic
            Resource: !Ref IndexLambdaTopicArn
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sns:Publish
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref IndexLambdaQueueArn





