AWSTemplateFormatVersion: 2010-09-09
Description: CSV / Raw To Zarr File Conversion

Parameters:
  DeploymentBucketName:
    Type: String
  LambdaRolePermissionsBoundary:
    Type: String
  Raw2ZarrLambdaMaxConcurrency:
    Type: Number
  Raw2ZarrLambdaTimeout:
    Type: Number
  Raw2ZarrLambdaMemorySize:
    Type: Number
  DataSetBucketName:
    Type: String
  ZarrFileBucketName:
    Type: String
  LogRetentionInDays:
    Type: Number
  DeadLetterTopicArn:
    Type: String
  Version:
    Type: String
  ZarrAccumulatorReadyTopicArn:
    Type: String
  Raw2ZarrTableArn:
    Type: String
  Raw2ZarrTableName:
    Type: String


Conditions:
  HasPermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref LambdaRolePermissionsBoundary

Resources:

  Raw2ZarrLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        Fn::If:
          - HasPermissionsBoundary
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${LambdaRolePermissionsBoundary}
          - AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrFileBucketName}/*
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrFileBucketName}
                Action:
                  - s3:ListBucket
        - PolicyName: SNS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Ref DeadLetterTopicArn
                  - !Ref ZarrAccumulatorReadyTopicArn
                Action:
                  - sns:Publish
        - PolicyName: DynamoDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Ref Raw2ZarrTableArn
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:DeleteItem

  Raw2ZarrLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub lambda/echofish-aws-raw2zarr-${Version}-docker.zip
      Handler: edu.colorado.cires.cmg.echofish.aws.lambda.raw2zarr.Raw2ZarrLambda::handleRequest
      Runtime: java11
      MemorySize: !Ref Raw2ZarrLambdaMemorySize
      Timeout: !Ref Raw2ZarrLambdaTimeout
      ReservedConcurrentExecutions: !Ref Raw2ZarrLambdaMaxConcurrency
      Role: !GetAtt Raw2ZarrLambdaRole.Arn
      Environment:
        Variables:
          SOURCE_BUCKET_NAME: !Ref DataSetBucketName
          ZARR_FILE_BUCKET_NAME: !Ref ZarrFileBucketName
          ZARR_ACCUMULATOR_READY_TOPIC_ARN: !Ref ZarrAccumulatorReadyTopicArn
          FILE_2_ZARR_TABLE: !Ref Raw2ZarrTableName

  Raw2ZarrLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Raw2ZarrLambda}
      RetentionInDays: !Ref LogRetentionInDays

  Raw2ZarrLambdaEvent:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Raw2ZarrLambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnFailure:
          Destination: !Ref DeadLetterTopicArn


Outputs:
  Raw2ZarrLambdaArn:
    Value: !GetAtt Raw2ZarrLambda.Arn
  Raw2ZarrLambdaName:
    Value: !Ref Raw2ZarrLambda




