AWSTemplateFormatVersion: 2010-09-09
Description: Zarr store to MVT

Parameters:
  DeploymentBucketName:
    Type: String
  LambdaRolePermissionsBoundary:
    Type: String
  Zarr2MvtLambdaTimeout:
    Type: Number
  Zarr2MvtLambdaMemorySize:
    Type: Number
  ZarrStoreBucketName:
    Type: String
  MvtTracklineSplitMs:
    Type: Number
  MvtBatchSize:
    Type: Number
  MvtTracklinePrecision:
    Type: Number
  MvtMaxZoomLevel:
    Type: Number
  MvtTracklineMinSimplificationTolerance:
    Type: Number
  MvtTracklineMaxSimplificationTolerance:
    Type: Number
  MvtUploadBuffers:
    Type: Number
  LogRetentionInDays:
    Type: Number
  Version:
    Type: String
  ZarrBucketRegion:
    Type: String
  OutputBucketUserAccessKeyPsName:
    Type: String
  OutputBucketUserSecretAccessKeyPsName:
    Type: String

Conditions:
  HasPermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref LambdaRolePermissionsBoundary

Resources:

  Zarr2MvtLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        Fn::If:
          - HasPermissionsBoundary
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${LambdaRolePermissionsBoundary}
          - AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrStoreBucketName}/*
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrStoreBucketName}
                Action:
                  - s3:ListBucket


  Zarr2MvtLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub lambda/echofish-aws-mvt-lambda-${Version}-lambda.zip
      Handler: edu.colorado.cires.cmg.echofish.aws.lambda.mvt.lambda.MvtLambda::handleRequest
      Runtime: java11
      MemorySize: !Ref Zarr2MvtLambdaMemorySize
      Timeout: !Ref Zarr2MvtLambdaTimeout
      ReservedConcurrentExecutions: 1
      Role: !GetAtt Zarr2MvtLambdaRole.Arn
      Environment:
        Variables:
          ZARR_BUCKET_NAME: !Ref ZarrStoreBucketName
          TRACKLINE_SPLIT_MS: !Ref MvtTracklineSplitMs
          BATCH_SIZE: !Ref MvtBatchSize
          GEO_JSON_PRECISION: !Ref MvtTracklinePrecision
          MAX_ZOOM_LEVEL: !Ref MvtMaxZoomLevel
          MIN_SIMPLIFICATION_TOLERANCE: !Ref MvtTracklineMinSimplificationTolerance
          MAX_SIMPLIFICATION_TOLERANCE: !Ref MvtTracklineMaxSimplificationTolerance
          S3_UPLOAD_BUFFERS: !Ref MvtUploadBuffers
          BUCKET_REGION: !Ref ZarrBucketRegion
          ZARR_BUCKET_ACCESS_KEY: !Sub "{{resolve:ssm:${OutputBucketUserAccessKeyPsName}}}"
          ZARR_BUCKET_SECRET_ACCESS_KEY: !Sub "{{resolve:ssm:${OutputBucketUserSecretAccessKeyPsName}}}"
  Zarr2MvtLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Zarr2MvtLambda}
      RetentionInDays: !Ref LogRetentionInDays

  Zarr2MvtLambdaEvent:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Zarr2MvtLambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
#      DestinationConfig:
#        OnFailure:
#          Destination: !Ref DeadLetterTopicArn


Outputs:
  Zarr2MvtLambdaArn:
    Value: !GetAtt Zarr2MvtLambda.Arn
  Zarr2MvtLambdaName:
    Value: !Ref Zarr2MvtLambda




