AWSTemplateFormatVersion: 2010-09-09
Description: Zarr store to MVT

Parameters:
  DeploymentBucketName:
    Type: String
  LambdaRolePermissionsBoundary:
    Type: String
  Zarr2GeoHashLambdaMaxConcurrency:
    Type: Number
  Zarr2GeoHashLambdaTimeout:
    Type: Number
  Zarr2GeoHashLambdaMemorySize:
    Type: Number
  ZarrStoreBucketName:
    Type: String
  GeoHashBucketName:
    Type: String
  GeoHashUploadBuffers:
    Type: Number
  LogRetentionInDays:
    Type: Number
  DeadLetterTopicArn:
    Type: String
  Version:
    Type: String
  GeoHashDoneTopicArn:
    Type: String


Conditions:
  HasPermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref LambdaRolePermissionsBoundary

Resources:

  Zarr2GeoHashLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        Fn::If:
          - HasPermissionsBoundary
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${LambdaRolePermissionsBoundary}
          - AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrStoreBucketName}/*
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrStoreBucketName}
                Action:
                  - s3:ListBucket
        - PolicyName: SNS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Ref DeadLetterTopicArn
                  - !Ref GeoHashDoneTopicArn
                Action:
                  - sns:Publish

  Zarr2GeoHashLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub lambda/echofish-aws-geohash-lambda-${Version}-lambda.zip
      Handler: edu.colorado.cires.cmg.echofish.aws.lambda.geohash.GeoHashLambda::handleRequest
      Runtime: java11
      MemorySize: !Ref Zarr2GeoHashLambdaMemorySize
      Timeout: !Ref Zarr2GeoHashLambdaTimeout
      ReservedConcurrentExecutions: !Ref Zarr2GeoHashLambdaMaxConcurrency
      Role: !GetAtt Zarr2GeoHashLambdaRole.Arn
      Environment:
        Variables:
          ZARR_BUCKET_NAME: !Ref ZarrStoreBucketName
          GEOHASH_BUCKET_NAME: !Ref GeoHashBucketName
          S3_UPLOAD_BUFFERS: !Ref GeoHashUploadBuffers
  Zarr2GeoHashLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Zarr2GeoHashLambda}
      RetentionInDays: !Ref LogRetentionInDays

  Zarr2GeoHashLambdaEvent:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Zarr2GeoHashLambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnFailure:
          Destination: !Ref DeadLetterTopicArn


Outputs:
  Zarr2GeoHashLambdaArn:
    Value: !GetAtt Zarr2GeoHashLambda.Arn
  Zarr2GeoHashLambdaName:
    Value: !Ref Zarr2GeoHashLambda





