AWSTemplateFormatVersion: 2010-09-09
Description: Zarr store to MVT

Parameters:
  DeploymentBucketName:
    Type: String
  LambdaRolePermissionsBoundary:
    Type: String
  Zarr2CruiseMvtLambdaTimeout:
    Type: Number
  Zarr2CruiseMvtLambdaMemorySize:
    Type: Number
  ZarrStoreBucketName:
    Type: String
  MvtBucketName:
    Type: String
  MvtTracklineSplitMs:
    Type: Number
  MvtBatchSize:
    Type: Number
  MvtTracklinePrecision:
    Type: Number
  MvtMaxZoomLevel:
    Type: Number
  MvtTracklineMinSimplificationTolerance:
    Type: Number
  MvtTracklineMaxSimplificationTolerance:
    Type: Number
  MvtUploadBuffers:
    Type: Number
  LogRetentionInDays:
    Type: Number
  DeadLetterTopicArn:
    Type: String
  Version:
    Type: String
  CruiseMvtDoneTopicArn:
    Type: String


Conditions:
  HasPermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref LambdaRolePermissionsBoundary

Resources:

  Zarr2CruiseMvtLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        Fn::If:
          - HasPermissionsBoundary
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${LambdaRolePermissionsBoundary}
          - AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrStoreBucketName}/*
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${ZarrStoreBucketName}
                Action:
                  - s3:ListBucket
        - PolicyName: SNS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Ref DeadLetterTopicArn
                  - !Ref CruiseMvtDoneTopicArn
                Action:
                  - sns:Publish

  Zarr2CruiseMvtLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub lambda/echofish-aws-mvt-lambda-${Version}-lambda.zip
      Handler: edu.colorado.cires.cmg.echofish.aws.lambda.mvt.lambda.MvtLambda::handleRequest
      Runtime: java11
      MemorySize: !Ref Zarr2CruiseMvtLambdaMemorySize
      Timeout: !Ref Zarr2CruiseMvtLambdaTimeout
      ReservedConcurrentExecutions: 1
      Role: !GetAtt Zarr2CruiseMvtLambdaRole.Arn
      Environment:
        Variables:
          ZARR_BUCKET_NAME: !Ref ZarrStoreBucketName
          TRACKLINE_SPLIT_MS: !Ref MvtTracklineSplitMs
          BATCH_SIZE: !Ref MvtBatchSize
          GEO_JSON_PRECISION: !Ref MvtTracklinePrecision
          MAX_ZOOM_LEVEL: !Ref MvtMaxZoomLevel
          MIN_SIMPLIFICATION_TOLERANCE: !Ref MvtTracklineMinSimplificationTolerance
          MAX_SIMPLIFICATION_TOLERANCE: !Ref MvtTracklineMaxSimplificationTolerance
          MVT_BUCKET_NAME: !Ref MvtBucketName
          S3_UPLOAD_BUFFERS: !Ref MvtUploadBuffers
  Zarr2CruiseMvtLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Zarr2CruiseMvtLambda}
      RetentionInDays: !Ref LogRetentionInDays

  Zarr2CruiseMvtLambdaEvent:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Zarr2CruiseMvtLambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnFailure:
          Destination: !Ref DeadLetterTopicArn


Outputs:
  Zarr2CruiseMvtLambdaArn:
    Value: !GetAtt Zarr2CruiseMvtLambda.Arn
  Zarr2CruiseMvtLambdaName:
    Value: !Ref Zarr2CruiseMvtLambda




