version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - ls $CODEBUILD_SRC_DIR_StackParameters
      - mvn -B -Dstack.name=$STACK_NAME -Ddeployment.stack.name=$DEPLOYMENT_STACK_NAME -Dstack.params="$CODEBUILD_SRC_DIR_StackParameters/echofish-parameters.json" -Ddeployment.params="$CODEBUILD_SRC_DIR_StackParameters/deployment-parameters.json" install validate
