version: 0.2

env:
  secrets-manager:
    DOCKER_PASSWORD: docker-cmgjenkins:password
    DOCKER_USERNAME: docker-cmgjenkins:username

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - mvn -B deploy
artifacts:
  files:
    - '**/*'