AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Stack

Parameters:
  OutputBucketUserAccessKeyPsName:
    Type: String
  OutputBucketUserSecretAccessKeyPsName:
    Type: String
  DevOutputBucketUserAlias:
    Type: String
    Default: ""
  RawSourceBucket:
    Type: String
    Default: "noaa-wcsd-pds"
  RawSourceBucketRegion:
    Type: String
    Default: "us-east-1"
  OutputBucketName:
    Type: String
    Default: "noaa-wcsd-zarr-pds"
  CalibrationBucket:
    Type: String
    Default: "noaa-wcsd-pds-index"
  CalibrationFileKey:
    Type: String
    Default: "calibrated_cruises.csv"

  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  RolePermissionsBoundary:
    Description: An optional permissions boundary to associate with roles
    Type: String
    Default: ""
  LogRetentionInDays:
    Type: Number
    Default: 30

  ### INDEXING ###
  IndexingLambdaImageTag:
    Type: String
    Default: 1.0.0.dev20230706162335
  IndexingLambdaMemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 4096
  IndexingLambdaTimeout:
    Type: Number
    MinValue: 1
    MaxValue: 900
    Default: 900

  ### CRUISE SPLITTER ###
  CruiseSplitterLambdaMemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 1024
  CruiseSplitterLambdaTimeout:
    Type: Number
    MinValue: 1
    MaxValue: 900
    Default: 240
  CruiseSplitterLambdaConcurrency:
    Type: Number
    MinValue: 1
    Default: 3

  ### RAW TO ZARR ###
  RawToZarrLambdaImageTag:
    Type: String
#    Default: 1.0.0.dev20230710204510
#    Default: 1.0.0.dev20230710213951
#    Default: 1.0.0.dev20230711164049
#    Default: 1.0.0.dev20230711183937
#    Default: 1.0.0.dev20230711192906
#    Default: 1.0.0.dev20230711205650
    Default: 1.0.0.dev20230711214025
  RawToZarrLambdaMemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 10240
  RawToZarrLambdaTimeout:
    Type: Number
    MinValue: 1
    MaxValue: 900
    Default: 900

#  RawToZarrDlqLambdaImageTag:
#    Type: String
#    Default: 1.0.0.dev20230524162855
#  RawToZarrDlqLambdaMemorySize:
#    Type: Number
#    MinValue: 128
#    MaxValue: 10240
#    Default: 2048
#  RawToZarrDlqLambdaTimeout:
#    Type: Number
#    MinValue: 1
#    MaxValue: 900
#    Default: 600

  ### CREATE EMPTY ZARR STORE ###
  CreateEmptyZarrStoreLambdaImageTag:
    Type: String
    Default: 1.0.0.dev20230524182219
  CreateEmptyZarrStoreLambdaMemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 2048
  CreateEmptyZarrStoreLambdaTimeout:
    Type: Number
    MinValue: 1
    MaxValue: 900
    Default: 600

#  ResampleAndWriteToZarrStoreLambdaImageTag:
#    Type: String
#    Default: 1.0.0.dev20230524192731
#  ResampleAndWriteToZarrStoreLambdaMemorySize:
#    Type: Number
#    MinValue: 128
#    MaxValue: 10240
#    Default: 2048
#  ResampleAndWriteToZarrStoreLambdaTimeout:
#    Type: Number
#    MinValue: 1
#    MaxValue: 900
#    Default: 600

#  RawToZarrErrorLambdaMemorySize:
#    Type: Number
#    MinValue: 128
#    MaxValue: 10240
#    Default: 1024
#  RawToZarrErrorLambdaTimeout:
#    Type: Number
#    MinValue: 1
#    MaxValue: 900
#    Default: 240
#  RawToZarrErrorLambdaConcurrency:
#    Type: Number
#    MinValue: 1
#    Default: 3

Conditions:
  CruiseSplitterLambdaIsRelease:
    Fn::Equals:
      - @CruiseSplitterLambda.version@
      - Fn::Join:
          - ""
          - Fn::Split:
              - "-SNAPSHOT"
              - @CruiseSplitterLambda.version@
#  RawToZarrErrorLambdaIsRelease:
#    Fn::Equals:
#      - @RawToZarrErrorLambda.version@
#      - Fn::Join:
#          - ""
#          - Fn::Split:
#              - "-SNAPSHOT"
#              - @RawToZarrErrorLambda.version@
  BucketDrainLambdaIsRelease:
    Fn::Equals:
      - @BucketDrainLambda.version@
      - Fn::Join:
          - ""
          - Fn::Split:
              - "-SNAPSHOT"
              - @BucketDrainLambda.version@

Resources:

  DynamoDbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackPrefix: !Ref StackPrefix
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/dynamo-db-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  MessagingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackPrefix: !Ref StackPrefix
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/messaging-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackPrefix: !Ref StackPrefix
        EnvironmentType:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-environment-type
        PermissionsBoundary: !Ref RolePermissionsBoundary
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket
        BucketDrainLambdaVersion: !If [ BucketDrainLambdaIsRelease, @BucketDrainLambda.version@, @BucketDrainLambda.version@@dashTimestamp@ ]
        DevOutputBucketUserAlias: !Ref DevOutputBucketUserAlias
        OutputBucketName: !Ref OutputBucketName
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/bucket-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  IndexingLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        LogRetentionInDays: !Ref LogRetentionInDays
        ImageTag: !Ref IndexingLambdaImageTag
        MemorySize: !Ref IndexingLambdaMemorySize
        Timeout: !Ref IndexingLambdaTimeout
        IndexTableName:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.IndexTableName
        IndexTableArn:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.IndexTableArn
        RawSourceBucket: !Ref RawSourceBucket
        CalibrationBucket: !Ref CalibrationBucket
        CalibrationFileKey: !Ref CalibrationFileKey
        IndexLambdaTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.IndexLambdaTopicArn
        DeadLetterTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.IndexDeadLetterTopicArn
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/indexing-lambda-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  CruiseSplitterLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket
        PermissionsBoundary: !Ref RolePermissionsBoundary
        MaxConcurrency: !Ref CruiseSplitterLambdaConcurrency
        Timeout: !Ref CruiseSplitterLambdaTimeout
        MemorySize: !Ref CruiseSplitterLambdaMemorySize
        InputBucketName: !Ref RawSourceBucket
        InputBucketRegion: !Ref RawSourceBucketRegion
        LogRetentionInDays: !Ref LogRetentionInDays
        DeadLetterTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.CruiseSplitterDeadLetterTopicArn
        Version: !If [CruiseSplitterLambdaIsRelease, @CruiseSplitterLambda.version@, @CruiseSplitterLambda.version@@dashTimestamp@]
        DoneTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.RawToZarrLambdaTopicArn
        FileInfoTableArn:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.FileInfoTableArn
        FileInfoTableName:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.FileInfoTableName
        TopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.CruiseSplitterLambdaTopicArn
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/cruise-splitter-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  # TODO: remove or replace
#  RawToZarrErrorLambdaStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      Parameters:
#        DeploymentBucketName:
#          Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket
#        PermissionsBoundary: !Ref RolePermissionsBoundary
#        MaxConcurrency: !Ref RawToZarrErrorLambdaConcurrency
#        Timeout: !Ref RawToZarrErrorLambdaTimeout
#        MemorySize: !Ref RawToZarrErrorLambdaMemorySize
#        LogRetentionInDays: !Ref LogRetentionInDays
#        Version: !If [ RawToZarrErrorLambdaIsRelease, @RawToZarrErrorLambda.version@, @RawToZarrErrorLambda.version@@dashTimestamp@ ]
#        FileInfoTableArn:
#          Fn::GetAtt:
#            - DynamoDbStack
#            - Outputs.FileInfoTableArn
#        FileInfoTableName:
#          Fn::GetAtt:
#            - DynamoDbStack
#            - Outputs.FileInfoTableName
#        TopicArn:
#          Fn::GetAtt:
#            - MessagingStack
#            - Outputs.CruiseSplitterDeadLetterTopicArn
#      TemplateURL:
#        Fn::Sub:
#          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/raw-to-zarr-error-stack_DELETE.yaml
#          - DeploymentBucketName:
#              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  RawToZarrLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentType:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-environment-type
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        LogRetentionInDays: !Ref LogRetentionInDays
        ImageTag: !Ref RawToZarrLambdaImageTag
        MemorySize: !Ref RawToZarrLambdaMemorySize
        Timeout: !Ref RawToZarrLambdaTimeout
        FileInfoTableArn:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.FileInfoTableArn
        FileInfoTableName:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.FileInfoTableName
        RawSourceBucket: !Ref RawSourceBucket
        OutputBucket:
          Fn::GetAtt:
            - BucketStack
            - Outputs.OutputBucketName
        RawToZarrLambdaTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.RawToZarrLambdaTopicArn
        OutputBucketUserAccessKeyPsName: !Ref OutputBucketUserAccessKeyPsName
        OutputBucketUserSecretAccessKeyPsName: !Ref OutputBucketUserSecretAccessKeyPsName
        DeadLetterTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.RawToZarrDeadLetterTopicArn
        DoneTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.CreateEmptyZarrStoreLambdaTopicArn
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/raw-to-zarr-lambda-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

#  RawToZarrDlqLambdaStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      Parameters:
#        RolePermissionsBoundary: !Ref RolePermissionsBoundary
#        LogRetentionInDays: !Ref LogRetentionInDays
#        ImageTag: !Ref RawToZarrDlqLambdaImageTag
#        MemorySize: !Ref RawToZarrDlqLambdaMemorySize
#        Timeout: !Ref RawToZarrDlqLambdaTimeout
#      TemplateURL:
#        Fn::Sub:
#          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/raw-to-zarr-dlq-lambda-stack_DELETE.yaml
#          - DeploymentBucketName:
#              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

  CreateEmptyZarrStoreLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentType:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-environment-type
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        LogRetentionInDays: !Ref LogRetentionInDays
        ImageTag: !Ref CreateEmptyZarrStoreLambdaImageTag
        MemorySize: !Ref CreateEmptyZarrStoreLambdaMemorySize
        Timeout: !Ref CreateEmptyZarrStoreLambdaTimeout
        FileInfoTableArn:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.FileInfoTableArn
        FileInfoTableName:
          Fn::GetAtt:
            - DynamoDbStack
            - Outputs.FileInfoTableName
        OutputBucket:
          Fn::GetAtt:
            - BucketStack
            - Outputs.OutputBucketName
        CreateEmptyZarrStoreLambdaTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.CreateEmptyZarrStoreLambdaTopicArn
        OutputBucketUserAccessKeyPsName: !Ref OutputBucketUserAccessKeyPsName
        OutputBucketUserSecretAccessKeyPsName: !Ref OutputBucketUserSecretAccessKeyPsName
        DeadLetterTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.CreateEmptyZarrStoreDeadLetterTopicArn
        DoneTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.CreateEmptyZarrStoreLambdaTopicArn
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/create-empty-zarr-store-lambda-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

#  ResampleAndWriteToZarrStoreLambdaStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      Parameters:
#        RolePermissionsBoundary: !Ref RolePermissionsBoundary
#        LogRetentionInDays: !Ref LogRetentionInDays
#        ImageTag: !Ref ResampleAndWriteToZarrStoreLambdaImageTag
#        MemorySize: !Ref ResampleAndWriteToZarrStoreLambdaMemorySize
#        Timeout: !Ref ResampleAndWriteToZarrStoreLambdaTimeout
#      TemplateURL:
#        Fn::Sub:
#          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/resample-and-write-to-zarr-store-lambda-stack.yaml
#          - DeploymentBucketName:
#              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket


