AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Stack

Parameters:
  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  RolePermissionsBoundary:
    Description: An optional permissions boundary to associate with roles
    Type: String
    Default: ""
  LogRetentionInDays:
    Type: Number
    Default: 30
  IndexingLambdaImageTag:
    Type: String
    Default: 1.0.0.dev20230523171328
  IndexingLambdaMemorySize:
    Type: Number
    MinValue: 128
    MaxValue: 10240
    Default: 2048
  IndexingLambdaTimeout:
    Type: Number
    MinValue: 1
    MaxValue: 900
    Default: 600




Resources:

  IndexingLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        LogRetentionInDays: !Ref LogRetentionInDays
        ImageTag: !Ref IndexingLambdaImageTag
        MemorySize: !Ref IndexingLambdaMemorySize
        Timeout: !Ref IndexingLambdaTimeout
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/indexing-lambda-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-deployment-bucket

