AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish MVT Generator

Parameters:
  Version:
    Type: String
  EC2LogGroup:
    Type: String
  EC2InstanceProfile:
    Type: String
  ImageId:
    Type: String
  InstanceType:
    Type: String
  VolumeSizeGB:
    Type: Number
  XYZTILESBUCKET:
    Type: String
  MBTILESBUCKET:
    Type: String
  MBTILESKEY:
    Type: String
  SQSARN:
    Type: String
  QUIETPERIODMS:
    Type: String
  DeploymentBucketName:
    Type: String

Resources:


  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          cfn:
            - cfn
          tippecanoe:
            - tippecanoe
        cfn:
          packages:
            yum:
              awslogs: []
              docker: []
          files:
            '/etc/awslogs/awscli.conf':
              content: !Sub |
                [default]
                region = ${AWS::Region}
                [plugins]
                cwlogs = cwlogs
              mode: '000644'
              owner: root
              group: root
            '/etc/awslogs/awslogs.conf':
              content: !Sub |
                [general]
                state_file = /var/lib/awslogs/agent-state
                [/var/log/dmesg]
                file = /var/log/dmesg
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/dmesg
                log_group_name = ${EC2LogGroup}
                [/var/log/messages]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/messages
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/messages
                log_group_name = ${EC2LogGroup}
                [/var/log/secure]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/secure
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/secure
                log_group_name = ${EC2LogGroup}
                [/var/log/cron]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/cron
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/cron
                log_group_name = ${EC2LogGroup}
                [/var/log/cfn-init.log]
                datetime_format = %Y-%m-%d %H:%M:%S
                file = /var/log/cfn-init.log
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/cfn-init.log
                log_group_name = ${EC2LogGroup}
                [/var/log/cfn-hup.log]
                datetime_format = %Y-%m-%d %H:%M:%S
                file = /var/log/cfn-hup.log
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/cfn-hup.log
                log_group_name = ${EC2LogGroup}
                [/var/log/cfn-init-cmd.log]
                datetime_format = %Y-%m-%d %H:%M:%S
                file = /var/log/cfn-init-cmd.log
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/cfn-init-cmd.log
                log_group_name = ${EC2LogGroup}
                [/var/log/cloud-init-output.log]
                file = /var/log/cloud-init-output.log
                log_stream_name = ${AWS::StackName}/{instance_id}/var/log/cloud-init-output.log
                log_group_name = ${EC2LogGroup}
                [/mvtgen/log/application.log]
                file = /mvtgen/log/application.log
                log_stream_name = ${AWS::StackName}/{instance_id}/mvtgen/log/application.log
                log_group_name = ${EC2LogGroup}
              mode: '000644'
              owner: root
              group: root
            '/etc/cfn/cfn-hup.conf':
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
              mode: '000400'
              owner: root
              group: root
            '/etc/cfn/hooks.d/cfn-auto-reloader.conf':
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2Instance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init --verbose --stack=${AWS::StackName} --region=${AWS::Region} --resource=EC2Instance
                runas=root
          services:
            sysvinit:
              docker:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                    - docker
              awslogs:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                    - awslogs
                files:
                  - '/etc/awslogs/awslogs.conf'
                  - '/etc/awslogs/awscli.conf'
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - '/etc/cfn/cfn-hup.conf'
                  - '/etc/cfn/hooks.d/cfn-auto-reloader.conf'
        tippecanoe:
          commands:
            "01":
              env:
                ECHOFISH_DEPLOYMENTBUCKET: !Ref DeploymentBucketName
                ECHOFISH_XYZTILESBUCKET: !Ref XYZTILESBUCKET
                ECHOFISH_MBTILESBUCKET: !Ref MBTILESBUCKET
                ECHOFISH_MBTILESKEY: !Ref MBTILESKEY
                ECHOFISH_SQSARN: !Ref SQSARN
                ECHOFISH_STACKNAME: !Ref AWS::StackName
                ECHOFISH_QUIETPERIODMS: !Ref QUIETPERIODMS
              command: !Sub 'set -ex && aws s3 cp s3://$ECHOFISH_DEPLOYMENTBUCKET/docker/echofish-aws-mvtgen-${Version}-docker.tar.gz / && docker load -i /echofish-aws-mvtgen-${Version}-docker.tar.gz && docker run -d --name mvtgen -e ECHOFISH_STACKNAME -e ECHOFISH_QUIETPERIODMS -e ECHOFISH_XYZTILESBUCKET -e ECHOFISH_MBTILESBUCKET -e ECHOFISH_MBTILESKEY -e ECHOFISH_SQSARN -v /mvtgen/log:/echofish-aws-mvtgen-${Version}/log cirescmg/echofish-aws-mvtgen:${Version} && while [ "`docker inspect -f {{.State.Health.Status}} mvtgen`" != "healthy" ]; do     sleep 2; done'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Properties:
      EbsOptimized: false
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref VolumeSizeGB
            VolumeType: gp2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          # Use the line below to ensure the CloudFormation helper scripts are updated to the latest version
          # Per: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html
          yum install -y aws-cfn-bootstrap
          #yum update -y
          retVal=$?
          if [ $retVal -ne 0 ]; then
              /opt/aws/bin/cfn-signal -e $retVal --stack ${AWS::StackName} --region ${AWS::Region} --resource=EC2Instance
          fi
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --configsets cfn,tippecanoe --region ${AWS::Region}
          retVal=$?
          if [ $retVal -ne 0 ]; then
              /opt/aws/bin/cfn-signal -e $retVal --stack ${AWS::StackName} --region ${AWS::Region} --resource=EC2Instance
          fi
          #INSTANCEID=$(curl -s -m 60 http://169.254.169.254/latest/meta-data/instance-id)
          /opt/aws/bin/cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource=EC2Instance